### ISSUE TITLE
DLSS Updater keeps failing on rescan (v4.2.1)

### ISSUE THREAD

**Issue by Quinta0** [Recol/DLSS-Updater#240]
**Version:** 4.2.1
**OS:** Cachyos 7.1.3
**Happens:** every time (or close to it) since updating to 4.2.1

## What's going on

Since updating to 4.2.1, every time I rescan my library and hit update, at least one DLL update fails. In this run it was `libxess_fg.dll` for Satisfactory.

## Possible root cause
Right at the start of the update run, this shows up 16 times in a row, once for every DLL the app tries to cache:

```
AttributeError: module 'os' has no attribute 'O_BINARY'
```

from this line in `high_performance_updater.py`:
```python
fd = os.open(dll_path, os.O_RDONLY | os.O_BINARY)

[CACHE] Loaded 0/16 source DLLs (0.0MB total)
```

Nothing goes into the cache. 

## How that turns into the crash you actually see

Because the cache is empty, the updater falls back to plain file-copy mode for every DLL. That mostly works, but then this happens:

```
ERROR - Error reading version from /home/quinta/.steam/steam/steamapps/common/Satisfactory/.../libxess_fg.dll: [Errno 2] No such file or directory
```
```
Traceback (most recent call last):
  File "dlss_updater/high_performance_updater.py", line 1567, in _apply_single_update
    if is_file_in_use(str(target_path)):
  File "dlss_updater/updater.py", line 281, in is_file_in_use
    with open(file_path, "rb"):
FileNotFoundError: [Errno 2] No such file or directory: '.../libxess_fg.dll'
```

Looking closer, I think this second issue happens because my Satisfactory install gets detected twice once under `~/.steam/steam/steamapps/...` and once under `~/.local/share/Steam/steamapps/...` (these are usually the same physical folder via a symlink, but the updater seems to be treating them as two separate copies of the game). It tries to back up and update the same DLLs twice, and on the second pass something's already moved/renamed, so the file "disappears" out from under it and `is_file_in_use()` crashes trying to open a file that's no longer there.

There's also a smaller cosmetic bug in there: the backup files are being named with a `.dlsss` extension instead of `.dll` e.g. `libxess_dx11.dlsss` which looks like an off-by-one in whatever code appends the backup suffix.

## End result

```
[PHASE 2] Updates: 5 succeeded, 1 failed, 142 skipped
```

So it "works" in that most files get updated and no dialog pops up, but one DLL silently fails to update every time, and the app is clearly not doing what it thinks it's doing on Linux since its whole caching layer is dead on arrival.

## TL;DR

1. **Main bug:** `os.O_BINARY` is Windows-only. On Linux it doesn't exist, so `load_source()` fails for every DLL, 100% of the time. Needs a platform check e.g. `flags = os.O_RDONLY | getattr(os, "O_BINARY", 0)`.
2. **Likely knock-on bug:** the game/library scanner seems to double-count Satisfactory via two paths that point to the same install, causing a duplicate update attempt and the `FileNotFoundError` crash in `is_file_in_use()`.
3. **Minor:** backup files get a broken `.dlsss` extension instead of `.dll`.

Happy to grab more logs or try a debug build if that'd help track it down further.

**Comment by Recol** [comment]
> **Version:** 4.2.1 **OS:** Cachyos 7.1.3 **Happens:** every time (or close to it) since updating to 4.2.1
> 
> ## What's going on
> Since updating to 4.2.1, every time I rescan my library and hit update, at least one DLL update fails. In this run it was `libxess_fg.dll` for Satisfactory.
> 
> ## Possible root cause
> Right at the start of the update run, this shows up 16 times in a row, once for every DLL the app tries to cache:
> 
> ```
> AttributeError: module 'os' has no attribute 'O_BINARY'
> ```
> 
> from this line in `high_performance_updater.py`:
> 
> fd = os.open(dll_path, os.O_RDONLY | os.O_BINARY)
> 
> [CACHE] Loaded 0/16 source DLLs (0.0MB total)
> Nothing goes into the cache.
> 
> ## How that turns into the crash you actually see
> Because the cache is empty, the updater falls back to plain file-copy mode for every DLL. That mostly works, but then this happens:
> 
> ```
> ERROR - Error reading version from /home/quinta/.steam/steam/steamapps/common/Satisfactory/.../libxess_fg.dll: [Errno 2] No such file or directory
> ```
> 
> ```
> Traceback (most recent call last):
>   File "dlss_updater/high_performance_updater.py", line 1567, in _apply_single_update
>     if is_file_in_use(str(target_path)):
>   File "dlss_updater/updater.py", line 281, in is_file_in_use
>     with open(file_path, "rb"):
> FileNotFoundError: [Errno 2] No such file or directory: '.../libxess_fg.dll'
> ```
> 
> Looking closer, I think this second issue happens because my Satisfactory install gets detected twice once under `~/.steam/steam/steamapps/...` and once under `~/.local/share/Steam/steamapps/...` (these are usually the same physical folder via a symlink, but the updater seems to be treating them as two separate copies of the game). It tries to back up and update the same DLLs twice, and on the second pass something's already moved/renamed, so the file "disappears" out from under it and `is_file_in_use()` crashes trying to open a file that's no longer there.
> 
> There's also a smaller cosmetic bug in there: the backup files are being named with a `.dlsss` extension instead of `.dll` e.g. `libxess_dx11.dlsss` which looks like an off-by-one in whatever code appends the backup suffix.
> 
> ## End result
> ```
> [PHASE 2] Updates: 5 succeeded, 1 failed, 142 skipped
> ```
> 
> So it "works" in that most files get updated and no dialog pops up, but one DLL silently fails to update every time, and the app is clearly not doing what it thinks it's doing on Linux since its whole caching layer is dead on arrival.
> 
> ## TL;DR
> 1. **Main bug:** `os.O_BINARY` is Windows-only. On Linux it doesn't exist, so `load_source()` fails for every DLL, 100% of the time. Needs a platform check e.g. `flags = os.O_RDONLY | getattr(os, "O_BINARY", 0)`.
> 2. **Likely knock-on bug:** the game/library scanner seems to double-count Satisfactory via two paths that point to the same install, causing a duplicate update attempt and the `FileNotFoundError` crash in `is_file_in_use()`.
> 3. **Minor:** backup files get a broken `.dlsss` extension instead of `.dll`.
> 
> Happy to grab more logs or try a debug build if that'd help track it down further.

Hiya thanks for the report, I've triaged down the issue of the crash, the second is misdiagnosed, it's a TOCTOU weird problem here with how the stack trace on failures work.

The third is _not_ a bug, this is intended, this is to provide compatibility with DLSS Swapper which uses this backup scheme, will fix the first two shortly.

**Comment by Recol** [comment]
@Quinta0 Should be resolved with version 4.2.2: https://github.com/Recol/DLSS-Updater/releases/tag/V4.2.2

**Comment by Quinta0** [comment]
Can confirm, the issue has been resolved. Thank you @Recol.
